---
language: ruby
bundler_args: --without development
script:
  - bundle exec rake validate
  - rubocop -D
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.2
    env: PUPPET_GEM_VERSION="~> 3.0"
notifications:
  email: false
